export const LOGIN_USER="LOGIN_USER"
export const LOGOUT_USER="LOGOUT_USER"
export const NEWS_LOADING="NEWS_LOADING"
export const ADD_POST="ADD_POST"
export const DELETE_POST="DELETE_POST"
export const EDIT_POST="EDIT_POST"
export const UPDATE="UPDATE"